import { useState } from "react";
import Header from "./components/Header";
import Footer from "./components/Footer";
import "./App.css";

type View="home"|"login"|"courses"|"quiz"|"results";
type Q={topic:string;level:"Easy"|"Medium";text:string;options:string[];answer:string;hint:string;retry?:Omit<Q,"retry">};
const quiz:Q[]=[
 {topic:"Encapsulation",level:"Medium",text:"What is the main purpose of encapsulation in OOP?",options:["Hide internal data and control access","Copy one class into another","Run programs faster","Avoid creating objects"],answer:"Hide internal data and control access",hint:"Encapsulation protects an object's state. It is often confused with inheritance.",retry:{topic:"Encapsulation",level:"Easy",text:"A bank account keeps its balance private and changes it through deposit methods. What OOP idea is this?",options:["Encapsulation","Inheritance","Looping","Compilation"],answer:"Encapsulation",hint:"Private data plus controlled methods is encapsulation."}},
 {topic:"Inheritance",level:"Medium",text:"Why would Programmer inherit from Employee?",options:["Reuse shared employee properties and methods","Prevent objects from being created","Make every method private","Remove constructors"],answer:"Reuse shared employee properties and methods",hint:"Inheritance models an is-a relationship and supports reuse.",retry:{topic:"Inheritance",level:"Easy",text:"If Dog inherits from Animal, which statement is true?",options:["Dog can reuse Animal features","Animal is deleted","Dog cannot have methods","They are the same object"],answer:"Dog can reuse Animal features",hint:"A child class can reuse features from its parent."}},
 {topic:"Polymorphism",level:"Medium",text:"What does polymorphism allow?",options:["One interface with different behavior per object","A class to have only one method","Data to be global","Objects to avoid constructors"],answer:"One interface with different behavior per object",hint:"The same method call can behave differently depending on the object.",retry:{topic:"Polymorphism",level:"Easy",text:"Cat and Dog both use speak() but give different sounds. What is this?",options:["Polymorphism","Encapsulation","A syntax error","A database"],answer:"Polymorphism",hint:"The same method name with different behavior is polymorphism."}}
];

export default function App(){
 const [view,setView]=useState<View>("home"),[name,setName]=useState(""),[student,setStudent]=useState(""),[i,setI]=useState(0),[q,setQ]=useState<Q>(quiz[0]),[choice,setChoice]=useState(""),[feedback,setFeedback]=useState(""),[retried,setRetried]=useState(false),[firstTry,setFirstTry]=useState(0),[mistakes,setMistakes]=useState<string[]>([]);
 const start=()=>setView(student?"courses":"login");
 const login=(e:React.FormEvent)=>{e.preventDefault();const user=name.trim();if(!user)return;const users=JSON.parse(localStorage.getItem("qw-students")||"[]") as string[];if(!users.includes(user))localStorage.setItem("qw-students",JSON.stringify([...users,user]));setStudent(user);setView("courses")};
 const begin=()=>{setI(0);setQ(quiz[0]);setChoice("");setFeedback("");setRetried(false);setFirstTry(0);setMistakes([]);setView("quiz")};
 const check=()=>{if(!choice)return;if(choice!==q.answer){setFeedback(q.hint+" Here is an easier question on the same idea.");setMistakes((x)=>x.includes(q.topic)?x:[...x,q.topic]);setQ(quiz[i].retry!);setChoice("");setRetried(true);return}if(!retried)setFirstTry((x)=>x+1);const next=i+1;if(next===quiz.length){setView("results");return}setI(next);setQ(quiz[next]);setChoice("");setFeedback("");setRetried(false)};
 return <div className="app"><Header onStart={start} onLogin={()=>setView("login")} student={student}/>
 {view==="home"&&<main><section className="hero"><div><p className="eyebrow">* A brighter way to revise</p><h1>Study less.<br/><em>Remember</em> more.</h1><p className="lead">Quizz-Wizz turns your notes into quizzes that adapt when you need more practice.</p><button className="primary" onClick={start}>Start a quick quiz -&gt;</button></div><aside className="preview"><small>Adaptive quiz - OOP</small><h2>Learn from every answer.</h2><p>Missed questions become easier follow-ups until you master the idea.</p></aside></section><section className="how" id="how"><h2>Your study sidekick.</h2><div><article><b>01 - Choose</b><p>Pick a course and start focused practice.</p></article><article><b>02 - Learn</b><p>Receive feedback and easier retries.</p></article><article><b>03 - Grow</b><p>Finish with a score sheet.</p></article></div></section></main>}
 {view==="login"&&<main className="screen"><section className="card"><p className="eyebrow">Your learning space</p><h1>Welcome to Quizz-Wizz.</h1><p>Create an account or return as an existing student. Names are stored in this browser.</p><form onSubmit={login}><label>Student name<input value={name} onChange={e=>setName(e.target.value)} placeholder="Enter your name" autoFocus/></label><button className="primary">Continue to courses</button></form></section></main>}
 {view==="courses"&&<main className="screen"><section className="card"><p className="eyebrow">Hello, {student}</p><h1>Choose your course.</h1><button className="course" onClick={begin}><b>OOP</b><strong>Object-Oriented Programming</strong><span>3 adaptive questions - starts at medium difficulty</span></button></section></main>}
 {view==="quiz"&&<main className="screen"><section className="card quiz"><div className="top"><span>OOP practice</span><span>Question {i+1} / {quiz.length}</span></div><span className="level">Difficulty: {q.level}</span><p className="eyebrow">{q.topic}</p><h1>{q.text}</h1><div className="options">{q.options.map(o=><button key={o} className={choice===o?"selected":""} onClick={()=>setChoice(o)}><i/> {o}</button>)}</div>{feedback&&<aside className="feedback"><b>Lets fix this together.</b><p>{feedback}</p></aside>}<button className="primary" disabled={!choice} onClick={check}>Check answer</button></section></main>}
 {view==="results"&&<main className="screen"><section className="card"><p className="eyebrow">Quiz complete</p><h1>Nice work, {student}.</h1><div className="score">{firstTry} / {quiz.length}</div><p>You answered every question correctly. Mistakes received easier same-topic follow-up questions.</p><div className="report">{quiz.map(x=><div key={x.topic}><span>{x.topic}</span><b>{mistakes.includes(x.topic)?"Mastered after practice":"Correct first try"}</b></div>)}</div><button className="primary" onClick={begin}>Try OOP again</button></section></main>}
 <Footer/></div>
} 
